defaults: &defaults
  google_maps_business_id: gme-westfieldltd
  google_maps_business_key: bE5iXqPOtk4BQzkJKbtpsHxWhRY=

development:
  <<: *defaults

test:
  <<: *defaults

systest:
  <<: *defaults

uat:
  <<: *defaults

production:
  <<: *defaults
