defaults: &defaults
  service_host: <%= Rails.env %>.dbg.westfield.com

development:
  <<: *defaults
  # You can do this if you want to test somthing!
  # service_host: systest.dbg.westfield.com

test:
  <<: *defaults

systest:
  <<: *defaults

uat:
  <<: *defaults

production:
  <<: *defaults
