defaults: &defaults
  product_service_url: http://product-service.<%= Rails.env %>.dbg.westfield.com/api/product/latest

development:
  <<: *defaults

test:
  <<: *defaults

systest:
  <<: *defaults

uat:
  <<: *defaults

production:
  <<: *defaults
