---
defaults: &defaults
  cloud_name: wlabs
  api_key: '126264366716471'
  api_secret: hrsUPxt6OVXvX_06NMyYKsARjUA
  enhance_image_tag: true
  static_image_support: true

development:
  <<: *defaults

test:
  <<: *defaults

systest:
  <<: *defaults

uat:
  <<: *defaults

production:
  <<: *defaults