common: &default_settings
  license_key: '504e11bc03bd8d450896c59ac27516ffacca2a7f'
  app_name: Customer Console Heroku
  monitor_mode: true
  developer_mode: false
  log_level: info
  browser_monitoring:
      auto_instrument: true
  audit_log:
    enabled: false
  capture_params: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true
  app_name: Customer Console Heroku (development)
test:
  <<: *default_settings
  monitor_mode: false
  app_name: Customer Console Heroku (test)
systest:
  <<: *default_settings
  monitor_mode: true
  app_name: Customer Console Heroku (systest)
uat:
  <<: *default_settings
  monitor_mode: true
  app_name: Customer Console Heroku (uat)
production:
  <<: *default_settings
  monitor_mode: true
staging:
  <<: *default_settings
  monitor_mode: true
  app_name: Customer Console Heroku (staging)

